/*
 * Copyright (C) 2014 SCVNGR, Inc. d/b/a LevelUp
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
package com.scvngr.levelup.core.util;

import android.support.annotation.NonNull;
import android.support.annotation.Nullable;

import com.scvngr.levelup.core.annotation.LevelUpApi;
import com.scvngr.levelup.core.annotation.LevelUpApi.Contract;

import net.jcip.annotations.ThreadSafe;

import java.util.Locale;

/**
 * This is a utility class to enforce preconditions.
 */
@LevelUpApi(contract = Contract.INTERNAL)
@ThreadSafe
public final class PreconditionUtil {

    /**
     *
     * @param objectToCheck Reference to check for nullness.
     * @param objectName Human-readable name of the object reference, to be formatted into any
     *            errors generated by this method.
     * @throws AssertionError if {@code objectToCheck} is null and
     *             {@link CoreLibConstants#IS_PARAMETER_CHECKING_ENABLED}.
     */
    public static void assertNotNull(@Nullable final Object objectToCheck,
            @NonNull final String objectName) {
        if (CoreLibConstants.IS_PARAMETER_CHECKING_ENABLED) {
            if (null == objectToCheck) {
                final String message = String.format(Locale.US, "%s cannot be null", objectName);
                throw new AssertionError(message);
            }
        }
    }

    /**
     * Private constructor prevents instantiation.
     *
     * @throws UnsupportedOperationException because this class cannot be instantiated.
     */
    private PreconditionUtil() {
        throw new UnsupportedOperationException("This class is non-instantiable");
    }
}
